### PR TITLE
msxml3 download issue

### PR DESCRIPTION
**Pull request by ricoderks**
Changed some small things to be able to download msxml3.msi

### CODE REVIEW

**Comment by sneumann** [comment]
Hi Rico, 
gosh, that patch touches an ugly part of my installation Dockerfile. 
Could it be that recent wine/winetricks can install msxml3 nowadays without that ? 
Instead of fixing the ugly hack getting rid of it in first place would be even cooler.

**Comment by sneumann** [comment]
IIRC this hack was because of https://github.com/Winetricks/winetricks/issues/500 
due to https://bugs.winehq.org/show_bug.cgi?id=33450

**Comment by sneumann** [comment]
There is also https://github.com/meier-rene/MSConvertGUI-docker/blob/master/Dockerfile by @meier-rene which is a bit more recent and likely cleaner. Rene packaged the GUI, which is able to convert Thermo (sic!) 
but not too useful in workflow systems. Difference is that `msconvert.exe` is written in C++, while the GUI is written in C#. Getting the vendor '*.dll' is apparently easier in C# than in C++.

**Comment by ricoderks** [comment]
I'll give it a try without msxml3, because this will probably will break more often in the future. And also have a look at what @meier-rene made. I also would like to have something to put in a workflow.

At the moment I'am got stuck at `msiexec /i /tmp/pwiz-setup.msi`. 
```
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
err:msi:dialog_run_message_loop Failed to create dialog L"PrepareDlg"
err:msi:dialog_run_message_loop Failed to create dialog L"MaintenanceWelcomeDlg"
err:msi:dialog_run_message_loop Failed to create dialog L"ProgressDlg"
err:msi:dialog_run_message_loop Failed to create dialog L"ExitDialog"
```

If I understand correctly it wants a display server.

**Comment by RJMW** [comment]
Hi @sneumann & @ricoderks 

I have been trying for a while to get a "msconvert" docker image up and running (for Thermo specific raw files). And I did run into the similar issues as @sneumann.

On a related note, there is a [.net library](http://planetorbitrap.com/rawfilereader#.WqEkBmrFJpg) that can be used to read .raw files in unix (using mono - less complicated then wine). We used it to access raw files directly and extract information that is not available from mzML. This works well but it doesn't help us directly with the conversion issue.

P.S. I am running into the same DISPLAY issue with @meier-rene docker file/image.

**Comment by ricoderks** [comment]
@RJMW I had no problems building the image and running the container. With MSconvertgui I just converted Sciex TripleTOF files to mzXML. Now trying it with msconvert.

**Comment by ricoderks** [comment]
To give an update: it also works if you use msconvert only it gives a huge amount of errors. I'll see if I can make some sort of mix of both Dockerfiles. I'am not an expert on this, but never been this close to convert MS files outside windows! :-)

**Comment by RJMW** [comment]
@ricoderks How did your resolve the display error/issue?

```
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

**Comment by meier-rene** [comment]
@RJMW have you also followed the instructions in the README?
Point 3: Allow local X11 connections from root

`xhost +local:root`

**Comment by ricoderks** [comment]
@RJMW  Sorry, I meant I didn't have the errors when I build MSconvertgui image from @meier-rene.

**Comment by ricoderks** [comment]
Hi all,

I got it working!! :-) First let me thank @sneumann  and @meier-rene for their awesome work!! I combined both Dockerfiles to get msconvert running as:

`docker run -v $HOME:/data msconvert ./Sample_1234.d -o ./ --mzXML --64 --zlib --filter "peakPicking true 1-" --filter "msLevel 1-"`

I tested it with converting a Bruker (impact HD) and Sciex (tripletof) file to mzXML. @RJMW I don't have any RAW files from Thermo.

**Comment by ricoderks** [comment]
Ok, that was not smart from me! There is a small.raw in this repository. I tried it and failed unfortunately @RJMW. @sneumann do you want me to send you a pr? I can imagine that it is maybe not interesting, because it can not convert Thermo files.

**Comment by sneumann** [comment]
Hi @ricoderks , I tried to `docker build` with your patches, but fail at `/usr/bin/xvfb-run winetricks --unattended dotnet35sp1` with the `Error: Access denied` mentioned elsewhere. Did you successfully `docker build` ? Which `docker --version` are you running ? I am on 1.13.1. Yours, Steffen

**Comment by ricoderks** [comment]
Hi @sneumann, I'am running docker version 17.05.0-ce, build 89658be in Ubuntu 16.04 LTS (64bit). I saw that this step worked for for me, but I got stuck on `msiexec /i /tmp/pwiz-setup.msi`. After this I started with trying to combine your Dockerfile and the one from @meier-rene. This is in [my own](https://github.com/ricoderks/MSConvert-docker) repository. Here I don't install dotnet35sp1 anymore, but the only thing is that it doesn't convert Thermo files :-( For me that is not that big of issue, because I only have Bruker and Sciex data files, but I was hoping that I could give something back. Unfortunately I'am not a wine expert and I don't understand the errors.

**Comment by sneumann** [comment]
Hi, given that I largely adopted the Dockerfile from @meier-rene, I would like to not merge this PR. 
If the master branch is lacking anything that this PR had, please re-open. I have also set up 
testing of the conversions for Bruker in the PhenoMeNal jenkins at 
http://phenomenal-h2020.eu/jenkins/view/%20B.-%20Container%20data%20tests/job/test-container-pwiz-bruker/
Yours, Steffen

**Pull request closed without merging**
